### ISSUE TITLE
Torghast Powers - UI Window issues

### ISSUE THREAD

**Issue by walldiv** [Kiatra/BlizzMove#56]
Confirmed that BlizzMove is the issue here by removing Blizzmove and the Torghast issues below work again:

1: When you accept a power - any power you try to click on aftewards has 0 action by clicking.
2: When you accept a power - most of the powers show the power name (top of its window) but the details/graphic is blanked.  https://puu.sh/HpJIo/41eba99ac4.png
3: This only took place in Skoldus Hall - Fractured Chambers was unnaffected on 2 different characters.

WHAT I TRIED:
1: /reload command - takes care of accepting powers but the power information inside of their respective windows is still blank.
2: Restarted Client/PC - 
3: Disabled BlizzMove addon - this successfully made everything work fine - determined Blizzmove needs update.

**Comment by Numynum** [comment]
I will test skoldus hall later, in the mean time, have you tried disabling all addons except blizzmove
additionally you can try disabling the playerchoice frame in the blizzmove settings

**Comment by Numynum** [comment]
after trying it on skuldus hall, I've not been able to reproduce the issue you're having
it might be another addon screwing things over
deleting layout-local.txt file might help (it's located at `[wow instal directory]/_retail_/WTF/Account/[your account id]/[servername]/[charactername]/layout-local.txt`)
other users have in the past had strange issues, that were resolved when resetting their cvars (typing `/console cvar_default` supposedly resets them)

**Comment by nivthefox** [comment]
> I will test skoldus hall later, in the mean time, have you tried disabling all addons except blizzmove?
> additionally you can try disabling the playerchoice frame in the blizzmove settings

I have tried disabling everything except BlizzMove and do still have the problem.  I have also confirmed that disabling BlizzMove alone fixes the problem, whereas no other addon being disabled does.  I will try disabling the playerchoice frame, as well as the layout-local.txt and resetting cvars, as you have suggested, each one at a time, and get back to you on how it impacts things.

**Comment by nivthefox** [comment]
It looks like disabling the PlayerChoice frame is a viable workaround for my specific situation.  

I've done some more extensive testing, and with only BlizzMove enabled, I get the following error after a few times opening and closing the selection:

```Message: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: PlayerChoiceFrame:SetPoint.
Time: Sun Mar 28 19:30:35 2021
Count: 2
Stack: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: PlayerChoiceFrame:SetPoint.
[string "=[C]"]: ?
[string "=[C]"]: in function `SetPoint'
[string "@Interface\AddOns\Blizzard_PlayerChoiceUI\Blizzard_PlayerChoiceUI.lua"]:586: in function `TryShow'
[string "@Interface\AddOns\Blizzard_PlayerChoiceUI\Blizzard_PlayerChoiceUI.lua"]:1929: in function <...\Blizzard_PlayerChoiceUI\Blizzard_PlayerChoiceUI.lua:1918>

Locals: (*temporary) = PlayerChoiceFrame {
 0 = <userdata>
 fixedPaddingAndSpacing = true
 optionLayout = <table> {
 }
 SetHeight = <function> defined =[C]:-1
 OnCleaned = <function> defined @Interface\AddOns\Blizzard_PlayerChoiceUI\Blizzard_PlayerChoiceUI.lua:749
 AdjustFramePaddingForCustomChoicePadding = <function> defined @Interface\AddOns\Blizzard_PlayerChoiceUI\Blizzard_PlayerChoiceUI.lua:886
 GetAdditionalRegions = <function> defined @Interface\SharedXML\LayoutFrame.lua:76
 OnShow = <function> defined @Interface\AddOns\Blizzard_PlayerChoiceUI\Blizzard_PlayerChoiceUI.lua:486
 LayoutChildren = <function> defined @Interface\SharedXML\LayoutFrame.lua:232
 UpdateNumActiveOptions = <function> defined @Interface\AddOns\Blizzard_PlayerChoiceUI\Blizzard_PlayerChoiceUI.lua:842
 FadeIn = <unnamed> {
 }
 FadeOut = <unnamed> {
 }
 hasPendingUpdate = false
 Update = <function> defined @Interface\AddOns\Blizzard_PlayerChoiceUI\Blizzard_PlayerChoiceUI.lua:892
 MarkClean = <function> defined @Interface\SharedXML\LayoutFrame.lua:105
 spacing = -80
 UpdateOptionWidgetRegistration = <function> defined @Interface\AddOns\Blizzard_PlayerChoiceUI\Blizzard_PlayerChoiceUI.lua:734
 GetLayoutChildren = <function> defined @Interface\SharedXML\LayoutFrame.lua:64
 SetPoint = <function> defined =[C]:-1
 IsDirty = <function> defined @Interface\SharedXML\LayoutFrame.lua:110
 OnLoad = <function> defined @Interface\AddOns\Blizzard_PlayerChoiceUI\Blizzard_PlayerChoiceUI.lua:475
 Layout = <function> defined @Interface\SharedXML\LayoutFrame.lua:155
 SetupTextureKits = <function> defined @Interface\AddOns\Blizzard_PlayerChoiceUI\Blizzard_PlayerChoiceUI.lua:525
 Option1 = <unnamed> {
 }
 fixedWidth = 284
 Option2 = <unnamed> {
 }
 optionsAligned = true
 IsLayoutFrame = <function> defined @Interface\SharedXML\LayoutFrame.lua:36
 GetPadding = <function> defined @Interface\SharedXML\LayoutFrame.lua:124
 MarkDirty = <function> defined @Interface\SharedXML\LayoutFrame.lua:90
 WidgetInit = <function> defined @Interface\AddOns\Blizzard_PlayerChoiceUI\Blizzard_PlayerChoiceUI.lua:728
 choiceID = 611
 TryShow = <function> defined @Interface\AddOns\Blizzard_PlayerChoiceUI\Blizzard_PlayerChoiceUI.lua:576
 optionInitHeight = 280
 OnFadeOutFinished = <function> defined @Interface\AddOns\Blizzard_PlayerChoiceUI\Blizzard_PlayerChoiceUI.lua:529
 HighStrataModelScene = <unnamed> {
 }
 optionData = <table> {
 }
 anOptionHasMultipleButtons = false
 dirty = false
 numActiveOptions = 2
 topPadding = 30
 SetupRewards = <function> defined @Interface\AddOns\Blizzard_PlayerChoiceUI\Blizzard_PlayerChoiceUI.lua:1057
 optionTitleFont = QuestFont_Huge {
 }
 optionHeaderTitleColor = <table> {
 }
 Option4 = <unnamed> {
 }
 QuestionText = <unnamed> {
 }
 optionDescriptionColor = <table> {
 }
 BlackBackground = <unnamed> {
 }
 rightPadding = 15
 uiTextureKit = "jailerstower"
 WidgetLayout = <function> defined @Interface\AddOns\Blizzard_PlayerChoiceUI\Blizzard_PlayerChoiceUI.lua:722
 frameData = <table> {
 }
 expand = true
 SetWidth = <function> defined =[C]:-1
 ThrowTooManyOptionsError = <function> defined @Interface\AddOns\Blizzard_PlayerChoiceUI\Blizzard_PlayerChoiceUI.lua:831
 CloseUIFromExitButton = <function> defined @Interface\AddOns\Blizzard_PlayerChoiceUI\Blizzard_PlayerChoiceUI.lua:666
 TryHide = <function> defined @Interface\AddOns\Blizzard_PlayerChoiceU```

**Comment by Numynum** [comment]
@nivthefox have you configured blizzmove to remember frame positions permanently?
if so, can you test with that setting turned off?

**Comment by Aotw75** [comment]
Sounds like the problem I have also, when using the option remember permantly only 1st power you choose works, all others after don't work, unless i /reload ui, If I choose remember session instead no issues choosing powers.
