### ISSUE TITLE
Error trying to rehook an already hooked frame

### ISSUE THREAD

**Issue by Maischter82** [Kiatra/BlizzMove#65]
1x Ace3\AceHook-3.0\AceHook-3.0-9.lua:180: Attempting to rehook already active hook OnMouseDown.
[string "=[C]"]: ?
[string "@Ace3\AceHook-3.0\AceHook-3.0-9.lua"]:180: in function <Ace3\AceHook-3.0\AceHook-3.0.lua:118>
[string "@Ace3\AceHook-3.0\AceHook-3.0-9.lua"]:411: in function `SecureHookScript'
[string "@BlizzMove\BlizzMove-v3.0.16.lua"]:687: in function <BlizzMove\BlizzMove.lua:645>
[string "=[C]"]: ?
[string "@BlizzMove\BlizzMove-v3.0.16.lua"]:736: in function `MakeFrameMovable'
[string "@BlizzMove\BlizzMove-v3.0.16.lua"]:753: in function `ProcessFrame'
[string "@BlizzMove\BlizzMove-v3.0.16.lua"]:785: in function `ProcessFrames'
[string "@BlizzMove\BlizzMove-v3.0.16.lua"]:882: in function <BlizzMove\BlizzMove.lua:874>
[string "=[C]"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
...
[string "@PetTracker\libs\WildAddon-1.0\WildAddon-1.0-1.lua"]:20: in function <...dOns\PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
[string "@PetTracker\libs\WildAddon-1.0\WildAddon-1.0-1.lua"]:56: in function <...dOns\PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Ace3\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:504: in function `UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:551: in function `CombatLog_LoadUI'
[string "@FrameXML\UIParent.lua"]:1394: in function <FrameXML\UIParent.lua:1277>

**Comment by Numynum** [comment]
hi, could you give us some more info?

are you playing retail or classic?
is there any error message from blizzmove in chat? something like `failed to make frame x movable`? if so, what frame?
the problem is probably due to another addon which you installed. simply disabling the frame that caused the error in the blizzmove settings should fix it

**Comment by Maischter82** [comment]
Hi Playing Retail 9.0.5.With you addon version .0.15 and older no bug... --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 02.05.21, 11:24 schrieb MarkW ***@***.***>:

   
  hi, could you give us some more info? 
  are you playing retail or classic? is there any error message from blizzmove in chat? something like failed to make frame x movable? if so, what frame? the problem is probably due to another addon which you installed. simply disabling the frame that caused the error in the blizzmove settings should fix it

**Comment by Maischter82** [comment]
Bug still exists. Without Blizzmove i never get it.

1x Ace3\AceHook-3.0\AceHook-3.0-9.lua:180: Attempting to rehook already active hook OnMouseDown.
[string "=[C]"]: ?
[string "@Ace3\AceHook-3.0\AceHook-3.0-9.lua"]:180: in function <Ace3\AceHook-3.0\AceHook-3.0.lua:118>
[string "@Ace3\AceHook-3.0\AceHook-3.0-9.lua"]:411: in function `SecureHookScript'
[string "@BlizzMove\BlizzMove-v3.0.17.lua"]:700: in function <BlizzMove\BlizzMove.lua:658>
[string "=[C]"]: ?
[string "@BlizzMove\BlizzMove-v3.0.17.lua"]:749: in function `MakeFrameMovable'
[string "@BlizzMove\BlizzMove-v3.0.17.lua"]:766: in function `ProcessFrame'
[string "@BlizzMove\BlizzMove-v3.0.17.lua"]:798: in function `ProcessFrames'
[string "@BlizzMove\BlizzMove-v3.0.17.lua"]:906: in function <BlizzMove\BlizzMove.lua:898>
[string "=[C]"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
...
[string "@PetTracker\libs\WildAddon-1.0\WildAddon-1.0-1.lua"]:20: in function <...dOns\PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua:18>
[string "@PetTracker\libs\WildAddon-1.0\WildAddon-1.0-1.lua"]:56: in function <...dOns\PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Ace3\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:504: in function `UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:551: in function `CombatLog_LoadUI'
[string "@FrameXML\UIParent.lua"]:1394: in function <FrameXML\UIParent.lua:1277>

**Comment by Maischter82** [comment]
Chat: Failed to make FlightMapFrame moveable.

**Comment by Numynum** [comment]
my previous post tells you the fix 👌
